In [1]:
import pandas as pd

In [9]:
df = pd.read_csv(r'orders.txt')

In [10]:
dfr=pd.read_csv(r'returns.txt')
dfr.head(2)

         order_id Return_Reason
0  CA-2020-104689   Wrong Items
1  CA-2020-105081   Wrong Items

In [15]:
dff = pd.merge(left=df,right=dfr,how='left',left_on='order_id',right_on='order_id')
dff

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_Reason
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,NaN
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,NaN
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,NaN
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,NaN
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,NaN
5,CA-2018-100391,2018-05-25,Barry Weirich,New York City,Office Supplies,OFF-PA-10001471,14.620,6.7252,NaN
6,CA-2018-100678,2018-04-18,Kunst Miller,Houston,Furniture,FUR-CH-10002602,317.058,-18.1176,NaN
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.460,9.7218,NaN
8,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760,Bad Quality
9,CA-2018-100860,2018-03-26,Cindy Stewart,Pomona,Office Supplies,OFF-LA-10001982,18.750,9.0000,NaN

In [18]:
#dff[dff['Return_Reason'].isnull()].groupby('category')['sales'].sum()
rdf=dff[dff['Return_Reason'].isnull()]
rdf.groupby('category')['sales'].sum()

category
Furniture          582901.5289
Office Supplies    284516.2270
Technology         174630.6580
Name: sales, dtype: float64

In [23]:
#Q2
dff = pd.merge(left=df,right=dfr,how='inner',left_on='order_id',right_on='order_id')
dff

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return_Reason
0,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760,Bad Quality
1,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.552,20.0970,Bad Quality
2,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.960,15.6332,Bad Quality
3,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.796,-168.9558,Bad Quality
4,CA-2018-103744,2018-02-23,Michael Grace,El Paso,Office Supplies,OFF-BI-10000320,4.428,-6.8634,Bad Quality
...,...,...,...,...,...,...,...,...,...
291,US-2021-136679,2021-11-14,Xylona Preis,Pasadena,Office Supplies,OFF-AR-10003582,45.040,4.5040,Others
292,US-2021-147886,2021-03-28,Dave Hallsten,Fairfield,Furniture,FUR-FU-10001095,26.480,10.0624,Others
293,US-2021-147998,2021-05-19,Sue Ann Reed,San Jose,Office Supplies,OFF-BI-10002082,133.120,49.9200,Wrong Items
294,US-2021-151127,2021-05-22,Rob Lucas,Los Angeles,Office Supplies,OFF-AR-10002445,49.560,18.8328,Wrong Items
295,US-2021-155999,2021-08-07,Jay Kimmel,San Diego,Office Supplies,OFF-BI-10000404,13.760,4.6440,Wrong Items

In [22]:
dff['city'].value_counts()

city
Los Angeles      50
Seattle          25
San Francisco    24
New York City    11
San Diego         9
                 ..
Redmond           1
York              1
Pueblo            1
Rome              1
Pharr             1
Name: count, Length: 119, dtype: int64

In [36]:
#Q3
dfn=dff.groupby('city')['Return_Reason'].nunique()
dfn[dfn.values==3]

city
Los Angeles      3
New York City    3
Name: Return_Reason, dtype: int64

In [46]:
#Q4
dff = pd.merge(left=df,right=dfr,how='left',left_on='order_id',right_on='order_id')
dfn= dff.groupby('city')['Return_Reason'].count()
dfn[dfn==0]

city
Aberdeen      0
Abilene       0
Akron         0
Alexandria    0
Allen         0
             ..
Woodstock     0
Woonsocket    0
Yonkers       0
Yucaipa       0
Yuma          0
Name: Return_Reason, Length: 412, dtype: int64

In [52]:
#Q5
#dff.groupby('city')['sales'].sum().sort_values(ascending=False).head(3)
dfn=dff.groupby('city')['sales'].sum()
dfn.sort_values(ascending=False).head(3)

city
New York City    115073.919
Los Angeles       79663.299
San Francisco     52590.648
Name: sales, dtype: float64

In [56]:
#Q6
dfr[dfr['Return_Reason'].isna()]

           order_id Return_Reason
11   CA-2020-114307           NaN
29   CA-2020-133368           NaN
107  CA-2018-105270           NaN
142  CA-2018-164721           NaN
149  CA-2019-105158           NaN

In [58]:
#Q7
dfr['Return_Reason'].fillna('others')

0      Wrong Items
1      Wrong Items
2      Wrong Items
3      Wrong Items
4      Wrong Items
          ...
291         Others
292         Others
293    Wrong Items
294    Wrong Items
295    Wrong Items
Name: Return_Reason, Length: 296, dtype: object

In [62]:
df.groupby('category').agg({'sales':'mean','profit':'mean'})

                      sales     profit
category
Furniture        356.212758   9.813403
Office Supplies  107.680040  18.906134
Technology       382.705186  75.452770

In [72]:
pip install fastparquet

Defaulting to user installation because normal site-packages is not writeable
Collecting fastparquet
  Downloading fastparquet-2025.12.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: pandas>=1.5.0 in c:\users\sudha\appdata\roaming\python\python313\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: numpy in c:\users\sudha\appdata\roaming\python\python313\site-packages (from fastparquet) (2.4.0)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.11.0-cp313-cp313-win_amd64.whl.metadata (681 bytes)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in c:\users\sudha\appdata\roaming\python\python313\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sudha\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sudha\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sudha\appdata\roaming\python\python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sudha\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2025.12.0-cp313-cp313-win_amd64.whl (667 kB)
   ---------------------------------------- 0.0/667.4 kB ? eta -:--:--
   ---------------------------------------- 667.4/667.4 kB 9.4 MB/s  0:00:00
Downloading cramjam-2.11.0-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 16.1 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Installing collected packages: fsspec, cramjam, fastparquet

   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ------------- -------------------------- 1/3 [cramjam]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   ---------------------------------------- 3/3 [fastparquet]

Successfully installed cramjam-2.11.0 fastparquet-2025.12.0 fsspec-2026.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
#df = pd.read_csv(r'orders.txt')
df.to_parquet('orders_p.parquet', engine='fastparquet')

In [78]:
df2=pd.read_parquet('orders_p.parquet', engine='fastparquet')

In [79]:
df2

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492