In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r'employee.csv')

In [14]:
df.head()

   emp_id emp_name  dept_id   salary  manager_id   age        Dob       dept
0     1.0    Ankit    100.0  12000.0         4.0  39.0  1/18/1987  Analytics
1     2.0    Mohit    100.0  18000.0         5.0  48.0  1/18/1978  Analytics
2     3.0    Vikas    100.0  12000.0         4.0  37.0  1/18/1989  Analytics
3     4.0    Rohit    100.0   6000.0         2.0  16.0  1/18/2010  Analytics
4     5.0    Mudit    200.0  12000.0         6.0  55.0  1/18/1971         IT

In [15]:
df.groupby('dept')['salary'].sum()

dept
Analytics    48000.0
HR            6600.0
IT           38000.0
Name: salary, dtype: float64

In [1]:
import pandas as pd 
import sqlalchemy as sal
import pyodbc

In [2]:
engine = sal.create_engine('mssql://Sudhanshu\\SQLEXPRESS/namastesql?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn=engine.connect()

In [4]:
df_products_db = pd.read_sql_query('select dept_id ,max(salary) as Total_sales from employee group by dept_id' ,conn)
df_products_db

   dept_id  Total_sales
0      100        18000
1      200        12000
2      300         6600
3      500         7000

In [6]:
df=pd.read_parquet(r"C:\Users\sudha\Downloads\part-00000-a9e77425-5fb4-456f-ba52-f821123bd193-c000.snappy.parquet")
df.head(30)

,id,first_name,last_name,email,gender,ip_address,cc,country,birthdate,salary,title,comments
0,1,Amanda,Jordan,ajordan0@com.com,Female,None,6759521864920116,Indonesia,3/8/1971,49756.53,Internal Auditor,1E+02
1,2,Albert,Freeman,afreeman1@is.gd,Male,218.111.175.34,,Canada,1/16/1968,150280.17,Accountant IV,
2,3,Evelyn,Morgan,emorgan2@altervista.org,Female,7.161.136.94,6767119071901597,Russia,2/1/1960,144972.51,Structural Engineer,
3,4,Denise,Riley,driley3@gmpg.org,Female,140.35.109.83,3576031598965625,China,4/8/1997,90263.05,Senior Cost Accountant,
4,5,Carlos,Burns,cburns4@miitbeian.gov.cn,,169.113.235.40,5602256255204850,South Africa,,NaN,,
5,6,Kathryn,White,kwhite5@google.com,Female,195.131.81.179,3583136326049310,Indonesia,2/25/1983,69227.11,Account Executive,
6,7,Samuel,Holmes,sholmes6@foxnews.com,Male,232.234.81.197,3582641366974690,Portugal,12/18/1987,14247.62,Senior Financial Analyst,
7,8,Harry,Howell,hhowell7@eepurl.com,Male,91.235.51.73,,Bosnia and Herzegovina,3/1/1962,186469.43,Web Developer IV,
8,9,Jose,Foster,jfoster8@yelp.com,Male,132.31.53.61,,South Korea,3/27/1992,231067.84,Software Test Engineer I,1E+02
9,10,Emily,Stewart,estewart9@opensource.org,Female,143.28.251.245,3574254110301671,Nigeria,1/28/1997,27234.28,Health Coach IV,
10,11,Susan,Perkins,sperkinsa@patch.com,Female,180.85.0.62,3573823609854134,Russia,,210001.95,,
11,12,Alice,Berry,aberryb@wikipedia.org,Female,246.225.12.189,4917830851454417,China,8/12/1968,22944.53,Quality Engineer,
12,13,Justin,Berry,jberryc@usatoday.com,Male,157.7.146.43,6331109912871813274,Zambia,8/15/1975,44165.46,Structural Analysis Engineer,
13,14,Kathy,Reynolds,kreynoldsd@redcross.org,Female,81.254.172.13,5537178462965976,Bosnia and Herzegovina,6/27/1970,286592.99,Librarian,
14,15,Dorothy,Hudson,dhudsone@blogger.com,Female,8.59.7.0,3542586858224170,Japan,12/20/1989,157099.71,Nurse Practicioner,<script>alert('hi')</script>
15,16,Bruce,Willis,bwillisf@bluehost.com,Male,239.182.219.189,3573030625927601,Brazil,,239100.65,,
16,17,Emily,Andrews,eandrewsg@cornell.edu,Female,29.231.180.172,30271790537626,Russia,4/13/1990,116800.65,Food Chemist,
17,18,Stephen,Wallace,swallaceh@netvibes.com,Male,152.49.213.62,5433943468526428,Ukraine,1/15/1978,248877.99,Account Representative I,
18,19,Clarence,Lawson,clawsoni@vkontakte.ru,Male,107.175.15.152,3544052814080964,Russia,,177122.99,,
19,20,Rebecca,Bell,rbellj@bandcamp.com,Female,172.215.104.127,,China,,137251.19,,
20,21,Diane,Stevens,dstevensk@cnet.com,Female,141.243.73.164,,Russia,6/5/1985,87978.22,Food Chemist,œ∑´®†¥¨ˆøπ“‘
21,22,Lawrence,Ramos,lramosl@sourceforge.net,Male,46.72.4.6,3537473810855655,Tanzania,,131283.64,,
22,23,Gregory,Barnes,gbarnesm@google.ru,Male,220.22.114.145,3538432455620641,Tunisia,1/23/1971,182233.49,Senior Sales Associate,사회과학원 어학연구소
23,24,Michelle,Ellis,mellisn@timesonline.co.uk,Female,239.81.215.135,3547383558025965,Tanzania,6/5/1964,278001.46,Tax Accountant,
24,25,Rachel,Perkins,rperkinso@lulu.com,Female,90.173.28.95,633313663891003209,Russia,,176178.75,,
25,26,Anthony,Lawrence,alawrencep@miitbeian.gov.cn,Male,121.211.242.99,564182969714151470,Japan,12/10/1979,170085.81,Electrical Engineer,
26,27,Henry,Henry,hhenryq@godaddy.com,Male,191.88.236.116,4905730021217853521,China,9/22/1995,284300.15,Nuclear Power Engineer,
27,28,Samuel,Hunter,shunterr@instagram.com,Male,72.190.230.173,5002353797389897,Brazil,9/21/1968,108950.24,Environmental Tech,
28,29,Jacqueline,Holmes,jholmess@ustream.tv,Female,47.141.224.95,3555934842115316,United States,,247939.52,,̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p...
29,30,Annie,Torres,atorrest@ning.com,Female,202.94.67.27,3530389861801215,Nigeria,5/20/1958,118310.72,Electrical Engineer,-1E+02

In [14]:
df.groupby('country')['salary'].sum()

country
"Bonaire               0.00
Afghanistan       242402.04
Aland Islands     259912.24
Albania           407562.74
Angola            229095.60
                    ...
Venezuela         637052.84
Vietnam          1138513.69
Yemen             558490.28
Zambia             44165.46
Zimbabwe          344654.25
Name: salary, Length: 120, dtype: float64