In [3]:
emp = {'name':'Ankit', 'gender':'Male', 'email':'ankit@gmail.com'}
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }
emp

{'name': ['Ankit', 'Rahul', 'Priya'],
 'gender': ['Male', 'Male', 'Female'],
 'email': ['ankit@gmail.com', 'rahul@gmail.com', 'priya@gmail.com']}

In [4]:
import pandas as pd

In [6]:
df_emp = pd.DataFrame(emp)
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [16]:
type(df_emp['name'])
#df_emp.info()
#df_emp.describe()

pandas.core.series.Series

In [17]:
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [21]:
#iloc is index/integer based
df_emp.iloc[1,2]
df_emp.iloc[1:3,0:2]
df_emp.iloc[1:3,0:2]

    name  gender
1  Rahul    Male
2  Priya  Female

In [25]:
# specific rows / columns
df_emp.iloc[[0,2],[0,2]]

pandas.core.frame.DataFrame

In [26]:
#loc is labeled based
df_emp

    name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [34]:
df_emp.loc[0:2,'name':'gender']

    name  gender
0  Ankit    Male
1  Rahul    Male
2  Priya  Female

In [48]:
df_emp.set_index('email',inplace=True)

In [59]:
df_emp
df_emp.sort_index(ascending=False)

                  name  gender
email
rahul@gmail.com  Rahul    Male
priya@gmail.com  Priya  Female
ankit@gmail.com  Ankit    Male

In [56]:
df_emp.loc['priya@gmail.com','name']
df_emp.loc['ankit@gmail.com':'priya@gmail.com','name':'gender']
df_emp.iloc[0:2]

                  name gender
email
ankit@gmail.com  Ankit   Male
rahul@gmail.com  Rahul   Male

In [61]:
df_emp.reset_index(inplace=True)

In [47]:
df_emp

             email   name  gender
0  ankit@gmail.com  Ankit    Male
1  rahul@gmail.com  Rahul    Male
2  priya@gmail.com  Priya  Female

In [63]:
fc= (df_emp['gender']=='Male')
fc

0     True
1     True
2    False
Name: gender, dtype: bool

In [67]:
df_emp[fc]

             email   name gender
0  ankit@gmail.com  Ankit   Male
1  rahul@gmail.com  Rahul   Male

In [69]:
fci = ~(df_emp['gender']=='Male')
fci

0    False
1    False
2     True
Name: gender, dtype: bool

In [70]:
df_emp[fci]

             email   name  gender
2  priya@gmail.com  Priya  Female

In [71]:
fcn = (df_emp['gender']!='Male')
df_emp[fcn]

             email   name  gender
2  priya@gmail.com  Priya  Female