In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('orders.txt')

In [10]:
#top and bottom n rows
df.head(20)
df.tail(10)

,order_id,order_date,customer_name,city,category,product_id,sales,profit
4999,US-2021-167570,2021-12-08,Emily Grady,Philadelphia,Furniture,FUR-CH-10003396,215.544,-58.5048
5000,US-2021-167920,2021-12-09,John Lee,Richmond,Office Supplies,OFF-AP-10000159,214.900,62.3210
5001,US-2021-168116,2021-11-04,Grant Thornton,Burlington,Office Supplies,OFF-AP-10002457,167.440,14.6510
5002,US-2021-168613,2021-10-08,Gary McGarr,New York City,Furniture,FUR-CH-10002372,145.764,3.2392
5003,US-2021-168690,2021-01-07,Thais Sissman,Ormond Beach,Office Supplies,OFF-BI-10000145,2.808,-1.9656
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [13]:
col = ['order_id','order_date','category']
df[col]

            order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [4]:
print(df.iloc[2:6,1:5])
print(df.loc[2:6,['city','sales']])

   order_date     customer_name           city         category
2  2018-03-14  Neil Französisch   Jacksonville  Office Supplies
3  2018-01-28   Jasper Cacioppo  New York City  Office Supplies
4  2018-04-08       Jim Mitchum       Glendale  Office Supplies
5  2018-05-25     Barry Weirich  New York City  Office Supplies
            city    sales
2   Jacksonville   91.056
3  New York City    3.928
4       Glendale    2.368
5  New York City   14.620
6        Houston  317.058

In [17]:
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [28]:
#to get unqiue values of a column
df['category'].unique()
type(df['category'])

pandas.core.series.Series

In [25]:
# to 
#pd.options.display.max_rows=100
df[['category','city']].value_counts()
#pd.options.display.max_rows=100

category         city
Office Supplies  New York City       257
                 Los Angeles         210
Furniture        New York City       157
Office Supplies  Philadelphia        152
                 San Francisco       149
                                    ...
                 North Charleston      1
                 Norfolk               1
                 Noblesville           1
                 Niagara Falls         1
                 Farmington            1
Name: count, Length: 987, dtype: int64

In [29]:
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [41]:
#fc = (df.category == 'Furniture' )
#fc = (df.category == 'Furniture' ) & (df.sales >= 2000 )
#df_fur= df[fc]
df_fur.reset_index(inplace=True)
df_fur

,index,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,207,CA-2018-116246,2018-09-12,Luke Weiss,New York City,Furniture,FUR-CH-10002024,3785.2920,420.5880
1,245,CA-2018-120474,2018-12-01,Resi Pölking,Madison,Furniture,FUR-CH-10001854,2807.8400,673.8816
2,352,CA-2018-128209,2018-11-17,Greg Tran,Buffalo,Furniture,FUR-BO-10002213,4007.8400,-50.0980
3,395,CA-2018-131926,2018-06-01,Dianna Wilson,Lakeville,Furniture,FUR-CH-10004063,2001.8600,580.5394
4,776,CA-2018-167199,2018-01-06,Maria Etezadi,Henderson,Furniture,FUR-CH-10004063,2573.8200,746.4078
5,943,CA-2019-111038,2019-12-01,Lindsay Castell,San Diego,Furniture,FUR-CH-10003973,2676.6720,267.6672
6,1020,CA-2019-116638,2019-01-28,Joseph Holt,Concord,Furniture,FUR-TA-10000198,4297.6440,-1862.3124
7,1025,CA-2019-117086,2019-11-08,Quincy Jones,Burlington,Furniture,FUR-BO-10004834,4404.9000,1013.1270
8,1066,CA-2019-120677,2019-05-31,Bill Donatelli,Minneapolis,Furniture,FUR-CH-10002320,2567.8400,770.3520
9,1293,CA-2019-137113,2019-12-01,Tamara Willingham,Seattle,Furniture,FUR-CH-10001215,2003.9200,125.2450
10,1324,CA-2019-139731,2019-10-15,Joel Eaton,Amarillo,Furniture,FUR-CH-10002024,2453.4300,-350.4900
11,1591,CA-2019-160227,2019-11-02,Emily Ducich,New York City,Furniture,FUR-CH-10002073,2621.3220,553.3902
12,1637,CA-2019-164301,2019-03-26,Ellis Ballard,Seattle,Furniture,FUR-TA-10001889,3393.6800,610.8624
13,1645,CA-2019-164777,2019-01-27,Sean Christensen,Los Angeles,Furniture,FUR-CH-10002024,2803.9200,0.0000
14,1762,CA-2020-104157,2020-07-25,Meg Tillman,Jackson,Furniture,FUR-TA-10004915,2430.0800,388.8128
15,1806,CA-2020-107104,2020-11-26,Maribeth Schnelling,Los Angeles,Furniture,FUR-BO-10002213,3406.6640,160.3136
16,1833,CA-2020-108987,2020-09-08,Anna Gayman,Houston,Furniture,FUR-BO-10004834,2396.2656,-317.1528
17,1921,CA-2020-113831,2020-05-30,Anna Häberlin,Springfield,Furniture,FUR-TA-10002645,2275.5000,386.8350
18,2051,CA-2020-122903,2020-05-27,Laura Armstrong,Detroit,Furniture,FUR-CH-10002024,3504.9000,700.9800
19,2562,CA-2020-155530,2020-12-17,Charles McCrossin,San Francisco,Furniture,FUR-TA-10004256,2003.5200,-325.5720
20,2789,CA-2020-169670,2020-12-25,Joe Elijah,New York City,Furniture,FUR-CH-10002331,2563.0560,313.2624
21,2800,CA-2021-100111,2021-09-20,Seth Vernon,New York City,Furniture,FUR-CH-10001215,2254.4100,375.7350
22,2851,CA-2021-102204,2021-05-01,Caroline Jumper,Jacksonville,Furniture,FUR-CH-10002024,2803.9200,0.0000
23,3180,CA-2021-118892,2021-08-17,Tom Prescott,Philadelphia,Furniture,FUR-CH-10002024,4416.1740,-630.8820
24,3256,CA-2021-122490,2021-11-13,Ted Trevino,Seattle,Furniture,FUR-CH-10001215,2404.7040,150.2940
25,3290,CA-2021-123967,2021-11-01,Sarah Foster,Bellingham,Furniture,FUR-TA-10003954,2665.6200,239.9058
26,3796,CA-2021-149559,2021-09-11,Karen Ferguson,Long Beach,Furniture,FUR-CH-10002320,2054.2720,256.7840
27,3805,CA-2021-150091,2021-10-12,Nora Paige,Lakewood,Furniture,FUR-BO-10003404,2154.9000,129.2940
28,4408,US-2019-126977,2019-09-17,Peter Fuller,New York City,Furniture,FUR-BO-10002213,2003.9200,-25.0490
29,4458,US-2019-150630,2019-09-17,Tracy Blumstein,Philadelphia,Furniture,FUR-BO-10004834,3083.4300,-1665.0522
30,4580,US-2020-126452,2020-08-21,Scot Coram,Los Angeles,Furniture,FUR-TA-10003569,2887.0560,180.4410
31,4705,US-2020-164196,2020-11-11,Alejandro Savely,Noblesville,Furniture,FUR-TA-10001950,2678.9400,241.1046

In [47]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [48]:
df_fur.to_csv('orders_furniture.csv')

In [52]:
fc = (df.category == 'Furniture' ) | (df.category == 'Technology' )
cat= ['Furniture','Technology']
fc =  (df['category'].isin(cat)) & (df['customer_name']== 'Ellis Ballard')
df[fc]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
1637,CA-2019-164301,2019-03-26,Ellis Ballard,Seattle,Furniture,FUR-TA-10001889,3393.680,610.8624
3934,CA-2021-156951,2021-10-01,Ellis Ballard,Seattle,Furniture,FUR-CH-10004997,451.152,0.0000
4198,US-2018-102631,2018-12-13,Ellis Ballard,Chicago,Furniture,FUR-FU-10003930,94.428,-42.4926