In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"orders.txt")

In [3]:
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [6]:
fc =( df.index %100==0)
df1=df[fc]
df1[['order_id','category','sales']]

            order_id         category     sales
0     CA-2018-100006       Technology   377.970
100   CA-2018-107573  Office Supplies    23.472
200   CA-2018-115791        Furniture   127.104
300   CA-2018-124723        Furniture   489.230
400   CA-2018-132500       Technology    49.980
500   CA-2018-141110  Office Supplies    40.540
600   CA-2018-151078  Office Supplies    49.632
700   CA-2018-159814        Furniture     4.272
800   CA-2018-169649  Office Supplies    20.388
900   CA-2019-107902  Office Supplies   470.360
1000  CA-2019-114811        Furniture   577.764
1100  CA-2019-123092        Furniture    77.952
1200  CA-2019-130792  Office Supplies     8.652
1300  CA-2019-137708  Office Supplies    37.940
1400  CA-2019-145324        Furniture    39.960
1500  CA-2019-153388        Furniture  1004.976
1600  CA-2019-161445  Office Supplies   140.736
1700  CA-2020-100083  Office Supplies    24.784
1800  CA-2020-106558       Technology   316.000
1900  CA-2020-113082        Furniture    40.480
2000  CA-2020-119018  Office Supplies     4.176
2100  CA-2020-125815  Office Supplies    12.420
2200  CA-2020-132094  Office Supplies     5.472
2300  CA-2020-138968        Furniture  1352.032
2400  CA-2020-145583        Furniture    43.120
2500  CA-2020-152121       Technology   271.992
2600  CA-2020-158099  Office Supplies  1141.470
2700  CA-2020-163755        Furniture   209.880
2800  CA-2021-100111        Furniture  2254.410
2900  CA-2021-104577  Office Supplies    87.600
3000  CA-2021-108910        Furniture   103.056
3100  CA-2021-115448        Furniture    88.920
3200  CA-2021-120222  Office Supplies    73.344
3300  CA-2021-124576  Office Supplies    54.896
3400  CA-2021-129707  Office Supplies     8.896
3500  CA-2021-134796       Technology   148.480
3600  CA-2021-140242  Office Supplies     6.408
3700  CA-2021-144827  Office Supplies   124.360
3800  CA-2021-149853  Office Supplies    17.920
3900  CA-2021-155089  Office Supplies    45.660
4000  CA-2021-160325       Technology   391.980
4100  CA-2021-165008  Office Supplies   295.056
4200  US-2018-103338  Office Supplies     7.980
4300  US-2018-147648  Office Supplies    81.980
4400  US-2019-123218        Furniture   359.058
4500  US-2019-168732  Office Supplies     1.780
4600  US-2020-132577  Office Supplies    23.616
4700  US-2020-163258  Office Supplies    11.232
4800  US-2021-116701  Office Supplies    66.284
4900  US-2021-140074  Office Supplies    25.680
5000  US-2021-167920  Office Supplies   214.900

In [7]:
df.head(5)

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288

In [17]:
order=(df['category'] =='Furniture') &(df['sales']>1000)  & (df['sales']<=1200)
df[order]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
155,CA-2018-111871,2018-03-18,Eileen Kiefer,San Francisco,Furniture,FUR-BO-10004218,1198.330,70.4900
374,CA-2018-130428,2018-03-31,Trudy Glocke,Tampa,Furniture,FUR-CH-10002965,1125.488,98.4802
631,CA-2018-153913,2018-12-16,Ken Black,Hialeah,Furniture,FUR-CH-10000988,1013.832,101.3832
834,CA-2019-102582,2019-09-15,Natalie Webber,Mobile,Furniture,FUR-CH-10004853,1056.860,306.4894
890,CA-2019-106320,2019-09-25,Emily Burns,Orem,Furniture,FUR-TA-10000577,1044.630,240.2649
924,CA-2019-110016,2019-11-29,Bill Tyler,Detroit,Furniture,FUR-CH-10002880,1106.910,121.7601
1084,CA-2019-121720,2019-06-11,Jim Epp,Lakeland,Furniture,FUR-CH-10003312,1123.920,-182.6370
1120,CA-2019-124891,2019-07-31,Rick Hansen,New York City,Furniture,FUR-TA-10002903,1090.782,-290.8752
1155,CA-2019-127509,2019-11-09,Adam Shillingsburg,Springfield,Furniture,FUR-TA-10002855,1024.380,215.1198
1205,CA-2019-130890,2019-11-02,Jas O'Carroll,Los Angeles,Furniture,FUR-TA-10002903,1038.840,51.9420
1500,CA-2019-153388,2019-08-01,Pauline Chand,Los Angeles,Furniture,FUR-TA-10003715,1004.976,-175.8708
1504,CA-2019-153549,2019-03-29,Sara Luxemburg,Jacksonville,Furniture,FUR-CH-10004086,1166.920,131.2785
1737,CA-2020-102092,2020-12-09,Paul MacIntyre,Springfield,Furniture,FUR-TA-10002530,1056.860,158.5290
1950,CA-2020-115917,2020-05-20,Rick Bensley,Vallejo,Furniture,FUR-FU-10000576,1049.200,272.7920
1965,CA-2020-116911,2020-09-15,Justin Deggeller,Twin Falls,Furniture,FUR-TA-10003473,1128.390,259.5297
2069,CA-2020-123946,2020-09-12,Anthony Johnson,Springfield,Furniture,FUR-CH-10002073,1059.120,307.1448
2202,CA-2020-132304,2020-06-14,Anthony Rawles,Seattle,Furniture,FUR-TA-10004619,1115.170,334.5510
2263,CA-2020-136406,2020-04-15,Bill Donatelli,San Francisco,Furniture,FUR-CH-10002024,1121.568,0.0000
2360,CA-2020-142958,2020-12-13,Rob Williams,Torrance,Furniture,FUR-TA-10000577,1114.272,41.7852
2505,CA-2020-152289,2020-08-26,Linda Cazamias,Pasadena,Furniture,FUR-CH-10002126,1024.716,-29.2776
2561,CA-2020-155516,2020-10-21,Michael Kennedy,Manchester,Furniture,FUR-BO-10002545,1043.920,271.4192
2856,CA-2021-102379,2021-12-02,Brenda Bowman,Oakland,Furniture,FUR-CH-10004983,1159.056,43.4646
3102,CA-2021-115602,2021-12-18,Doug Jacobs,New York City,Furniture,FUR-CH-10001708,1141.938,139.5702
3150,CA-2021-117702,2021-11-28,Lindsay Shagiari,Baltimore,Furniture,FUR-FU-10000576,1049.200,272.7920
3326,CA-2021-126067,2021-08-28,Kristina Nunn,Seattle,Furniture,FUR-TA-10000617,1137.750,250.3050
3644,CA-2021-142342,2021-07-17,Anthony Johnson,Apple Valley,Furniture,FUR-BO-10002613,1194.165,210.7350
3689,CA-2021-144491,2021-03-27,Caroline Jumper,Houston,Furniture,FUR-BO-10001811,1023.332,-30.0980
4238,US-2018-117968,2018-08-05,Ricardo Sperren,Meriden,Furniture,FUR-CH-10002335,1133.350,294.6710
4251,US-2018-123183,2018-11-19,Georgia Rosenberg,Wilmington,Furniture,FUR-BO-10000362,1025.880,235.9524
4254,US-2018-125521,2018-03-14,Christine Kargatis,Chesapeake,Furniture,FUR-CH-10003379,1139.920,284.9800
4279,US-2018-137869,2018-03-28,Christina VanderZanden,Des Moines,Furniture,FUR-TA-10003954,1184.720,106.6248
4299,US-2018-147627,2018-01-20,Hunter Lopez,Jonesboro,Furniture,FUR-CH-10002331,1067.940,224.2674
4304,US-2018-148838,2018-03-17,Christine Phan,New York City,Furniture,FUR-TA-10001950,1071.576,-553.6476
4423,US-2019-134558,2019-12-19,Peter McVee,Dover,Furniture,FUR-TA-10003473,1053.164,-105.3164
4471,US-2019-157154,2019-01-10,Michael Moore,New York City,Furniture,FUR-TA-10001889,1018.104,-373.3048
4713,US-2020-167339,2020-01-21,Tamara Dahlen,San Diego,Furniture,FUR-CH-10000785,1013.488,76.0116
4733,US-2021-102890,2021-06-30,Sheri Gordon,New York City,Furniture,FUR-TA-10000577,1044.630,-295.9785
4773,US-2021-110576,2021-11-28,Ross Baird,Philadelphia,Furniture,FUR-FU-10000576,1007.232,75.5424
4985,US-2021-164056,2021-04-29,Filia McAdams,Dublin,Furniture,FUR-TA-10001307,1048.350,-69.8900
4989,US-2021-165456,2021-11-30,Trudy Brown,Philadelphia,Furniture,FUR-CH-10003981,1079.316,-15.4188

In [20]:
df.nunique()

order_id         5009
order_date       1236
customer_name     793
city              531
category            3
product_id       1639
sales            3592
profit           4185
dtype: int64

In [26]:
cy=['New York City','Seattle','Los Angeles']
fc = (df['city'].isin(cy)) & (df['profit']<0)
df[fc]

,order_id,order_date,customer_name,city,category,product_id,sales,profit
27,CA-2018-101931,2018-10-28,Todd Sumrall,Los Angeles,Furniture,FUR-BO-10001337,616.998,-36.2940
87,CA-2018-106439,2018-10-31,Greg Guthrie,Los Angeles,Furniture,FUR-CH-10003833,146.352,-9.1470
159,CA-2018-112158,2018-12-02,David Philippe,New York City,Furniture,FUR-BO-10003272,883.920,-110.4900
189,CA-2018-114517,2018-12-23,Tiffany House,New York City,Furniture,FUR-TA-10001676,53.316,-19.5492
234,CA-2018-119151,2018-11-25,Mike Pelletier,New York City,Furniture,FUR-BO-10003159,275.952,-37.9434
...,...,...,...,...,...,...,...,...
4728,US-2021-101784,2021-07-06,Patrick O'Brill,Los Angeles,Furniture,FUR-CH-10001146,122.136,-13.7403
4733,US-2021-102890,2021-06-30,Sheri Gordon,New York City,Furniture,FUR-TA-10000577,1044.630,-295.9785
4826,US-2021-121251,2021-03-26,Gary McGarr,New York City,Furniture,FUR-BO-10001918,257.568,-28.9764
4982,US-2021-163300,2021-09-15,Erica Smith,Los Angeles,Furniture,FUR-CH-10003396,184.752,-20.7846
4983,US-2021-163657,2021-09-02,Janet Lee,Los Angeles,Furniture,FUR-TA-10004607,236.528,-2.9566

In [36]:
df_of= (df[df['category']=='Office Supplies'])
uni_cty = df_of['city'].unique()
uni_cty

array(['Jacksonville', 'New York City', 'Glendale', 'Jackson', 'Pomona',
       'Roswell', 'Salt Lake City', 'Chicago', 'Mesa', 'Springfield',
       'Seattle', 'Philadelphia', 'Miami', 'Richmond', 'Brentwood',
       'Las Vegas', 'Charlotte', 'Alexandria', 'Indianapolis',
       'San Francisco', 'Huntsville', 'Mount Vernon', 'Fairfield',
       'El Paso', 'Houston', 'Sandy Springs', 'Laredo', 'San Diego',
       'Escondido', 'Provo', 'Pasadena', 'Madison', 'Athens', 'Gilbert',
       'Bowling Green', 'Billings', 'Los Angeles', 'Cottage Grove',
       'Lawrence', 'Columbus', 'Plainfield', 'Long Beach', 'Romeoville',
       'Tempe', 'Fort Lauderdale', 'Hollywood', 'Newark', 'Lakewood',
       'Santa Clara', 'Brownsville', 'Great Falls', 'Columbia', 'Akron',
       'Little Rock', 'Arlington', 'Naperville', 'Chula Vista',
       'Rock Hill', 'Rochester', 'Hempstead', 'Logan', 'Lancaster',
       'Cincinnati', 'Sioux Falls', 'Johnson City', 'Minneapolis',
       'Margate', 'Virginia Beach', 'Lakeville', 'Baltimore', 'Orange',
       'Aurora', 'Wausau', 'Owensboro', 'Grand Prairie', 'Freeport',
       'Cary', 'Troy', 'Dallas', 'Saint Petersburg', 'Beaumont', 'Utica',
       'Fayetteville', 'Omaha', 'Atlanta', 'Oswego', 'Port Arthur',
       'Pleasant Grove', 'Boca Raton', 'Watertown', 'Riverside',
       'Redondo Beach', 'Chesapeake', 'Medina', 'Salem', 'Murray',
       'Henderson', 'Appleton', 'Rancho Cucamonga', 'Cedar Hill',
       'North Miami', 'Taylor', 'Moreno Valley', 'Phoenix', 'San Jose',
       'Detroit', 'Bangor', 'Denver', 'Yonkers', 'New Rochelle', 'Revere',
       'Bellevue', 'Hamilton', 'Hialeah', 'Clarksville', 'Fresno',
       'Meriden', 'Midland', 'Beverly', 'Lodi', 'Anaheim', 'Bristol',
       'Westland', 'Nashville', 'Avondale', 'Lafayette', 'Orlando',
       'Eau Claire', 'Portland', 'Dearborn Heights', 'Coon Rapids',
       'Decatur', 'San Antonio', 'Wilmington', 'Albuquerque', 'Knoxville',
       'Vallejo', 'Woodstock', 'Vacaville', 'Memphis', 'Huntington Beach',
       'Scottsdale', 'Kent', 'Louisville', 'Deltona', 'Bossier City',
       'Montgomery', 'Dover', 'Fort Worth', 'Delray Beach', 'Saint Louis',
       'Asheville', 'Marietta', 'West Jordan', 'Tigard', 'Norwich',
       'Medford', 'Auburn', 'Franklin', 'Spokane', 'Smyrna', 'Quincy',
       'Suffolk', 'Cleveland', 'Mcallen', 'Sparks', 'Milwaukee',
       'San Bernardino', 'Pueblo', 'Lubbock', 'Missoula', 'Clinton',
       'Tallahassee', 'Raleigh', 'Hampton', 'New Bedford', 'Altoona',
       'Yucaipa', 'Daytona Beach', 'Lansing', 'Bolingbrook', 'Lebanon',
       'Saint Charles', 'Cambridge', 'Des Moines', 'Vineland',
       'Plantation', 'Bloomington', 'Leominster', 'Coral Springs',
       'Woonsocket', 'Bozeman', 'Chester', 'Peoria', 'Norfolk',
       'Murfreesboro', 'Austin', 'Haltom City', 'Baytown', 'Florence',
       'Morristown', 'Ann Arbor', 'Reading', 'Wilson', 'Murrieta',
       'Roseville', 'Colorado Springs', 'Oceanside', 'Carrollton',
       'North Charleston', 'Layton', 'Thornton', 'Toledo',
       'West Palm Beach', 'Allen', 'Las Cruces', 'Eagan',
       'Sterling Heights', 'Concord', 'Redlands', 'Buffalo', 'Greensboro',
       'Tamarac', 'Noblesville', 'Santa Barbara', 'Santa Fe', 'Rockford',
       'Rockville', 'Bakersfield', 'Bedford', 'Royal Oak', 'Oxnard',
       'Thousand Oaks', 'Manchester', 'Farmington', 'Durham', 'Woodbury',
       'Bartlett', 'Perth Amboy', 'New Castle', 'Macon', 'Superior',
       'Lindenhurst', 'Santa Ana', 'Lewiston', 'Lakeland', 'Chico',
       'Bayonne', 'Temecula', 'South Bend', 'Boise', 'Newport News',
       'Tulsa', 'Sacramento', 'Holland', 'Conroe', 'Rome', 'La Crosse',
       'Oakland', 'Arlington Heights', 'Visalia', 'Sierra Vista',
       'Round Rock', 'Irving', 'San Luis Obispo', 'Marion', 'Orem',
       'Yuma', 'Lowell', 'Port Saint Lucie', 'Mobile', 'Gulfport',
       'Georgetown', 'Amarillo', 'Bridgeton', 'Stockton', 'Davis',
       'Niagara Falls', 'Edinburg', 'Cuyahoga Falls', 'Edmond', 'Monroe',
       'Pembroke Pines', 'Deer Park', 'Waco', 'East Orange', 'Jonesboro',
       'Hendersonville', 'Providence', 'The Colony', 'Thomasville',
       'Middletown', 'Greenville', 'Palm Coast', 'Oklahoma City',
       'San Clemente', 'Grand Rapids', 'Marysville', 'Warwick', 'Malden',
       'Urbandale', 'Goldsboro', 'Gresham', 'Carlsbad', 'Apopka',
       'Waterbury', 'Redwood City', 'Wichita', 'Fremont', 'Warner Robins',
       'North Las Vegas', 'Washington', 'Tampa', 'Olathe', 'Broken Arrow',
       'Overland Park', 'Shelton', 'Milford', 'Saint Paul', 'Westfield',
       'La Porte', 'Salinas', 'Vancouver', 'Elmhurst', 'Iowa City',
       'Atlantic City', 'Trenton', 'Reno', 'Pocatello', 'Hesperia',
       'Lincoln Park', 'Waukesha', 'Mishawaka', 'Edmonds', 'Parma',
       'Covington', 'Garland', 'Apple Valley', 'Belleville',
       'Fort Collins', 'Pine Bluff', 'Chattanooga', 'Odessa',
       'Independence', 'Everett', 'Harlingen', 'Miramar', 'Garden City',
       'Dublin', 'Torrance', 'Mansfield', 'Redmond', 'Renton', 'Wheeling',
       'Fargo', 'Inglewood', 'Greenwood', 'Westminster', 'Bryan',
       'College Station', 'Elyria', 'Burlington', 'Plano', 'Hoover',
       'La Mesa', 'Boynton Beach', 'Waterloo', 'Lorain', 'Summerville',
       'Canton', 'Chandler', 'Skokie', 'Loveland', 'Cranston',
       'Green Bay', 'Hickory', 'Grand Island', 'Hattiesburg', 'Saginaw',
       'Oak Park', 'Chapel Hill', 'Sunnyvale', 'Grove City', 'Melbourne',
       'Costa Mesa', 'Port Orange', 'Tucson', 'Commerce City', 'Longview',
       'San Mateo', 'Maple Grove', 'Muskogee', 'Tuscaloosa', 'Coppell',
       'Rogers', 'Keller', 'Camarillo', 'Pompano Beach', 'Hillsboro',
       'Missouri City', 'Springdale', 'Coachella', 'Lake Charles',
       'Southaven', 'Laguna Niguel', 'New Brunswick', 'Corpus Christi',
       'Meridian', 'Abilene', 'Paterson', 'Manteca', 'Clovis',
       'Homestead', 'Mission Viejo', 'Aberdeen', 'York', 'Helena',
       'Lawton', 'Tyler', 'Portage', 'Mesquite', 'Santa Maria',
       'Allentown', 'Frankfort', 'Antioch', 'Sheboygan', 'Gastonia',
       'Pensacola', 'Grapevine', 'Englewood', 'Kenner', 'Highland Park',
       'Park Ridge', 'Charlottesville', 'Pearland', 'Hagerstown', 'Pasco',
       'Danville', 'Woodland', 'Jupiter', 'Nashua', 'Ormond Beach',
       'Elkhart'], dtype=object)

In [38]:
df.head(5)

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288

In [41]:
fc = df[df['city']=='New York City']
fc['category'].value_counts()

category
Office Supplies    257
Furniture          157
Technology          36
Name: count, dtype: int64

In [76]:
#df.set_index('order_id', inplace=True)
lst=['CA-2019-115742','CA-2020-111682','CA-2019-149587','US-2020-150147','CA-2020-138520']
df.loc[lst]

,order_date,customer_name,city,category,product_id,sales,profit
order_id,,,,,,,
CA-2019-115742,2019-04-18,Darren Powers,New Albany,Furniture,FUR-CH-10003061,89.990,17.0981
CA-2020-111682,2020-06-17,Ted Butterfield,Troy,Furniture,FUR-CH-10003968,319.410,7.0980
CA-2019-149587,2019-01-31,Karl Braun,Minneapolis,Furniture,FUR-FU-10003799,53.340,16.5354
US-2020-150147,2020-04-25,John Lucas,Philadelphia,Office Supplies,OFF-BI-10001153,20.724,-13.8160
CA-2020-138520,2020-04-08,Jeremy Lonsdale,New York City,Furniture,FUR-BO-10002268,388.704,-4.8588

In [77]:
lst=['CA-2019-115742','CA-2020-111682','CA-2019-149587','US-2020-150147','CA-2020-138520']
df1=df.loc[lst,['order_date','sales','category']]
df1

                order_date    sales         category
order_id
CA-2019-115742  2019-04-18   89.990        Furniture
CA-2020-111682  2020-06-17  319.410        Furniture
CA-2019-149587  2019-01-31   53.340        Furniture
US-2020-150147  2020-04-25   20.724  Office Supplies
CA-2020-138520  2020-04-08  388.704        Furniture

In [81]:
lst=['CA-2019-115742','CA-2020-111682','CA-2019-149587','US-2020-150147','CA-2020-138520']
df1=df.loc[lst,'order_date':'city']
df1

                order_date    customer_name           city
order_id
CA-2019-115742  2019-04-18    Darren Powers     New Albany
CA-2020-111682  2020-06-17  Ted Butterfield           Troy
CA-2019-149587  2019-01-31       Karl Braun    Minneapolis
US-2020-150147  2020-04-25       John Lucas   Philadelphia
CA-2020-138520  2020-04-08  Jeremy Lonsdale  New York City

In [82]:
df.sort_index(ascending = False)

,order_date,customer_name,city,category,product_id,sales,profit
order_id,,,,,,,
US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492
US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
...,...,...,...,...,...,...,...
CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113

In [83]:
df.to_csv('index_change')